### ISSUE TITLE
Possibility of licensing mico32 under Apache or MIT license?

### ISSUE THREAD

**Issue by TeroK** [wyvernSemi/mico32#1]
Hi!

I fell in love of your implementation of LM32 ISS. The code is extremely readable and well written, very exceptional quality I must say. I also love the way you decode and execute instructions with LUT function pointers instead of huge switch case that I have seen in most ISS's. I have inspected about dozen of open source ISS and mico32 stands out as clear winner in my eyes.

I'm planning to create an "embeddable virtual machine library" that could be used add safe/sandboxed scriptability to any C/C++ application, and I think some ISS could be the tech behind that. Benefits of using ISS over some script interpreters would be the compactness of the VM implementation and the ability to use gcc to produce the ebmeddable executables that run inside main app as a sub programs/plugins. Mico32 is very tempting choice for this project.

However, I think GPL can be quite limiting in libraries because it's viral nature. Any app that uses GPL library (even dynamically linked), needs to be GPL licensed as well. It limits the audience of such library quite a bit, which I see undesirable.

I'm writing to ask whether you would it be possible to obtain a copy of mico32 with Apache 2.0, MIT, or similar license that would make it widely usable as a library. 

How does it sound to you as mico32 author?

Thanks and Best regards,
Tero

**Comment by wyvernSemi** [comment]
Hi Tero,

In principle I have no objection to such an arrangement. I'm not so familiar with the Apache 20 and MIT licenses as I am with the GPL license. I chose GPL as a default just to make sure some coverage was in place before publication, but the aim is to make the code free for people to use as they wish. Give me a little time to go over the licenses you mention to make sure there's nothing in there that would prevent me from keeping control of the original. If all is good (and I have no reason to doubt it), then maybe I can bundle a package for you with one of the licenses you mention. 

best regards,

Simon

**Comment by wyvernSemi** [comment]
Hi Tero,

I have created a mico32 bundle released under the MIT license. The LICENSE file is updated, and all the relevant headers in the source. The bundle is attached. It is the same as the original code, except it has had the doc directory removed and the linux binaries in the test directory removed to make it compact. These can be downloaded from the github repository. Any issues with it, let me know.

[mico32-MIT.zip](https://github.com/wyvernSemi/mico32/files/2431366/mico32-MIT.zip)

**Comment by TeroK** [comment]
Thank you very much :) I'll throw you a link to a repo if I get this going. Right now I'm also evaluating web assembly interpreter "wac", but mico32 seems far better written and optimized to me.
